// Generated by `cargo run -p compose-rust --bin codegen`. DO NOT EDIT.
@file:OptIn(
    kotlin.js.ExperimentalWasmJsInterop::class,
    kotlin.wasm.ExperimentalWasmInterop::class,
)

package dev.darkpyonix.composerust.ui.platform

import kotlin.wasm.WasmExport
import kotlin.wasm.WasmImport

// The web boundary.
//
// One WebAssembly.Memory holds both modules. The Kotlin module defines and exports it,
// because a Kotlin/Wasm module cannot import one, and the Host's module is linked against
// it, so a batch is read where the Host wrote it and no byte of it is copied.
//
// Every call below is a wasm import, and no call has JavaScript on it. Each one is bound to
// a function of the generated trampoline module, which passes its arguments on with
// `call_indirect` through a table whose slots hold the Host's exports. The table is what
// lets this module be instantiated before the Host exists, which it has to be, because the
// Host imports this module's memory. The loader creates the table and the trampoline before
// this module is instantiated; `installHost` fills the slots once the Host is running.
// A call is one wasm `call` and one `call_indirect`: no encoding, no copy, no queue.
//
// The other direction needs no trampoline. The Host is instantiated second, so the page
// hands it the function object Kotlin exports below, and the engine binds that edge as a
// wasm call.

/**
 * The first address that belongs to the Host's module.
 *
 * Below it is this module's `kotlin.wasm.unsafe` allocator; at and above it are the
 * Host's data, stack and heap. Two allocators hand out addresses in one memory, and an
 * overlap does not crash, it draws the wrong screen, so every address that crosses is
 * checked against this line.
 */
const val RUST_REGION_BASE: Int = 4194304

/**
 * The batch record the Host writes, field by field.
 *
 * A wasm32 `#[repr(C)]` layout: two four byte fields and then an eight byte one, which
 * the padding before it puts at 8. The Host's generated shims assert this against the
 * layout its compiler chose, so a disagreement stops that build.
 */
/** where the batch starts, as an address in the shared memory. */
const val BATCH_ADDRESS_OFFSET: Int = 0
/** the batch's length in bytes. */
const val BATCH_LENGTH_OFFSET: Int = 4
/** the handler's synchronous result. */
const val BATCH_RESULT_OFFSET: Int = 8

/** How long that record is, padding included. */
const val BATCH_BYTES: Int = 16

/**
 * Where the event buffer starts inside the block the Host lends this side.
 *
 * The out record comes first and the event buffer follows it. Both belong to the Host,
 * because `kotlin.wasm.unsafe` only hands out addresses inside a scope and this side
 * needs two buffers that outlive every scope it could open.
 */
const val EVENT_BUFFER_OFFSET: Int = 16

/** How much room there is to encode one event into. */
const val EVENT_BUFFER_BYTES: Int = 4096

/** `Init`, which calls `compose_rust_host_init` through slot 0 of the trampoline. */
@WasmImport("./compose-rust-host.gen.mjs", "compose_rust_host_web_init")
external fun hostInit(handshake: Int, handshakeLength: Int, out: Int): Int

/** `DispatchEvent`, which calls `compose_rust_host_dispatch_event` through slot 1 of the trampoline. */
@WasmImport("./compose-rust-host.gen.mjs", "compose_rust_host_web_dispatch_event")
external fun hostDispatchEvent(event: Int, eventLength: Int, out: Int): Int

/** `RenderFrame`, which calls `compose_rust_host_render_frame` through slot 2 of the trampoline. */
@WasmImport("./compose-rust-host.gen.mjs", "compose_rust_host_web_render_frame")
external fun hostRenderFrame(frameTimeNanos: Long, out: Int): Int

/** `ReleaseBatch`, which calls `compose_rust_host_release_batch` through slot 3 of the trampoline. */
@WasmImport("./compose-rust-host.gen.mjs", "compose_rust_host_web_release_batch")
external fun hostReleaseBatch(out: Int): Int

/** `Shutdown`, which calls `compose_rust_host_shutdown` through slot 4 of the trampoline. */
@WasmImport("./compose-rust-host.gen.mjs", "compose_rust_host_web_shutdown")
external fun hostShutdown(): Int

/**
 * Instantiates the Host on this module's memory, points the trampoline at it, and answers
 * with the address of the block it lends back: the record a call reports into, and the
 * buffer an event is encoded in. Zero means there is no Host on this page.
 *
 * Called once, from `main`. That is the first moment at which both halves exist: this
 * module's own instantiation created the memory the Host imports, and the page compiled the
 * Host's module before that started.
 */
@JsFun(
    """() => {
  const compiled = globalThis.__composeRustHostModule;
  if (!compiled) return 0;
  const table = globalThis.__composeRustHostTable;
  if (!table) {
    throw new Error('compose-rust: the trampoline table is missing. The loader module ' +
      'creates it, and this module imports the loader, so a page without it was not ' +
      'built from the generated files.');
  }
  const memory = wasmExports.memory;
  const pages = memory.buffer.byteLength / 65536;
  // This module's memory starts at zero pages and the Host's import declares a minimum,
  // so the two module types do not match until this has run.
  if (pages < 128) memory.grow(128 - pages);
  // The wasm-bindgen placeholders dioxus-core brings in through subsecond. A browser will
  // not instantiate a module with an import nobody supplied, used or not, and their names
  // carry a per-version hash, so this answers whatever is asked rather than a list that
  // would go stale. Nothing on the boundary goes near one.
  const unbound = (namespace) => new Proxy({}, {
    get: (_, name) => () => {
      throw new Error('compose-rust: the Host called ' + namespace + '.' + String(name) +
        ', which is a wasm-bindgen import this page does not provide. Nothing on the ' +
        'boundary uses one, so a call here means the Host reached JavaScript through a ' +
        'dependency rather than through the boundary.');
    },
  });
  const host = new WebAssembly.Instance(compiled, {
    env: { memory },
    compose_rust_renderer: {
      // The exported function object itself, not a closure around it: bound this way the
      // engine builds no JavaScript frame for the call.
      compose_rust_renderer_request_frame:
        wasmExports.compose_rust_renderer_request_frame,
    },
    __wbindgen_placeholder__: unbound('__wbindgen_placeholder__'),
    __wbindgen_externref_xform__: unbound('__wbindgen_externref_xform__'),
  }).exports;
  const block = host.compose_rust_host_web_start();
  if (block < 4194304) {
    // Either the Host could not start, or its data landed in the half of the memory this
    // module's allocator uses. The second draws a wrong screen instead of failing, so
    // neither is allowed to become the first boundary call: the table stays empty.
    throw new Error('compose-rust: the Host reported its boundary block at ' + block +
      ', which is not inside the region above 4194304 that it was linked into. ' +
      'Check that it was linked with --import-memory and --global-base.');
  }
  // The trampoline's slots, in the order its functions call them. The exported function
  // objects themselves, so a call through a slot is wasm to wasm.
  table.set(0, host.compose_rust_host_web_init);
  table.set(1, host.compose_rust_host_web_dispatch_event);
  table.set(2, host.compose_rust_host_web_render_frame);
  table.set(3, host.compose_rust_host_web_release_batch);
  table.set(4, host.compose_rust_host_web_shutdown);
  return block;
}""",
)
external fun installHost(): Int

/**
 * Called by the Host when work done off the frame loop needs one.
 *
 * A browser tab is one thread, so this arrives on the same thread that will answer it.
 * It only bumps a counter the frame clock observes, so any number of requests between
 * two frames become one frame. The page also calls it once after the Host is installed,
 * which is what gets the first tree drawn.
 */
@WasmExport("compose_rust_renderer_request_frame")
fun onFrameRequested() {
    FrameRequests.request()
}
